import {
    ActionCard,
    CardType,
    CardRarity,
    SpeedLevel,
    BoardLayer,
} from "@types";

/**
 * Follow Me! - Unique Action Card (Alpha Set #050)
 *
 * Requires: Control Alrecht Barkstep, Scoutmaster
 * Effect: Teleport target summon you control to an unoccupied space adjacent to Alrecht Barkstep
 * Speed: Action Speed
 * Destination: Recharge Pile
 * Attribute: Neutral
 * Rarity: Special (Unique)
 *
 * Note: This card is generated by Alrecht Barkstep, Scoutmaster and is not available in packs
 */
export const followMe: ActionCard = {
    // Core card identity
    id: "1-083-i-follow-me!-Alpha",
    name: "Follow Me!",
    type: CardType.ACTION,
    rarity: CardRarity.COMMON,
    description:
        "Teleport target summon you control to an unoccupied space adjacent to Alrecht Barkstep, Scoutmaster. This is not movement.",
    attribute: "neutral",

    // Action card specific properties
    speed: SpeedLevel.ACTION,
    destinationPile: "removed",

    // Requirements to play this card
    requirements: [
        {
            id: "control-alrecht-barkstep",
            type: "controlsSpecificSummon",
            parameters: {
                summonId: "039-alrecht-barkstep-Alpha",
                zone: "inPlay",
            },
        },
    ],

    // Card effects
    effects: [
        {
            id: "teleport-summon",
            type: "positionEntity",
            parameters: {
                relativeToEntity: "039-alrecht-barkstep-Alpha",
                relativeToEntityType: "summon",
                adjacentOnly: true,
                unoccupiedOnly: true,
                validLayers: [
                    BoardLayer.NONOBSTRUCTING_BUILDINGS,
                    BoardLayer.TERRAIN,
                ],
            },
            targeting: {
                type: "single",
                restrictions: [
                    {
                        type: "summon",
                        zone: "inPlay",
                        controller: "self", // Must target your own summon
                    },
                ],
            },
        },
    ],
};

export default followMe;
