import { ActionCard, CardType, CardRarity, SpeedLevel } from "@types";

/**
 * Healing Touch - Unique Action Card (Alpha Set #131)
 *
 * Generated by: Paladin role when in play
 * Requires: Control a Paladin summon (as caster)
 * Effect: Heal target summon you control within range 1 of the caster
 * Formula: caster.SPI * (1 + base_power/100) with 20 base power
 * Can crit: Yes (1.5x multiplier)
 * Speed: Action Speed
 * Destination: Removed from game after use
 * Attribute: Light
 * Rarity: Uncommon
 *
 * Note: This card is generated by Paladin role and is not available in packs
 */
export const healingTouch: ActionCard = {
    // Core card identity
    id: "131-healing_touch-Alpha",
    name: "Healing Touch",
    type: CardType.ACTION,
    rarity: CardRarity.UNCOMMON,
    description:
        "A Paladin healing spell that restores a significant amount of health to a target summon.",
    attribute: "light",

    // Action card specific properties
    speed: SpeedLevel.ACTION,
    destinationPile: "removed",

    // Requirements to play the card
    requirements: [
        {
            id: "control-paladin-caster",
            type: "controlsSummon",
            parameters: {
                controller: "self",
                zone: "inPlay",
                roleId: "031-paladin-Alpha",
                minimumCount: 1,
            },
        },
    ],

    // Effects when playing the card
    effects: [
        {
            id: "healing-touch-heal",
            type: "heal",
            parameters: {
                healingFormula: "caster.SPI * (1 + base_power/100)",
                healingType: "magical",
                healingAttribute: "light",
                basePower: 20,
                canCrit: true,
                critMultiplier: 1.5,
                critFormula: "standard",
                caster: {
                    type: "summon",
                    zone: "inPlay",
                    controller: "self",
                    roleId: "031-paladin-Alpha",
                },
            },
            targeting: {
                type: "single",
                restrictions: [
                    {
                        type: "summon",
                        zone: "inPlay",
                        controller: "self",
                        rangeFromCaster: 1,
                    },
                ],
            },
        },
    ],
};
