// Unique Cards - Alpha Set
// These cards are not available in packs and are generated by specific named summons

import { followMe } from "./follow-me";
import { healingTouch } from "./healing-touch";

export const uniqueCards = [followMe, healingTouch];

export { followMe, healingTouch };
